import { useEffect, useState } from 'react';
import { Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Mail, Send } from 'lucide-react-native';
import { collection, onSnapshot, orderBy, query, where } from 'firebase/firestore';
import { httpsCallable } from 'firebase/functions';
import { auth, db, functions } from '../lib/firebase';
import { enqueue } from '../lib/offlineQueue';
import { ScreenContainer } from '../components/ScreenContainer';

type Message = { id: string; contenu: string; expediteurId: string; destinataireId: string; createdAt?: { seconds?: number } };

export default function MessagesScreen() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [recipientId, setRecipientId] = useState('');
  const [content, setContent] = useState('');
  const [sending, setSending] = useState(false);
  useEffect(() => { let stop: () => void = () => undefined; const load = async () => { if (!db || !auth?.currentUser) return; const claims = await auth.currentUser.getIdTokenResult(); const schoolId = String(claims.claims.school_id ?? ''); if (!schoolId) return; const messagesQuery = query(collection(db, 'ecoles', schoolId, 'messages'), where('destinataireId', '==', auth.currentUser.uid), orderBy('createdAt', 'desc')); stop = onSnapshot(messagesQuery, (snapshot) => setMessages(snapshot.docs.map((item) => ({ id: item.id, ...item.data() } as Message))), () => setMessages([])); }; void load(); return () => stop(); }, []);
  const send = async () => { if (!recipientId.trim() || !content.trim()) { Alert.alert('Message incomplet', 'Saisissez un destinataire et un message.'); return; } const payload = { destinataireId: recipientId.trim(), contenu: content.trim() }; setSending(true); try { if (functions) await httpsCallable(functions, 'sendMessage')(payload); else await enqueue('sendMessage', payload); setContent(''); Alert.alert('Message envoyé', 'Votre message a été transmis.'); } catch { await enqueue('sendMessage', payload); Alert.alert('Hors connexion', 'Le message sera envoyé automatiquement au retour du réseau.'); } finally { setSending(false); } };
  return <ScreenContainer><View style={styles.heading}><View><Text style={styles.eyebrow}>MESSAGERIE</Text><Text style={styles.title}>Messages</Text><Text style={styles.caption}>Les conversations restent limitées à votre établissement.</Text></View><Mail color="#630ed4" size={28} /></View><View style={styles.compose}><TextInput value={recipientId} onChangeText={setRecipientId} placeholder="Identifiant du destinataire" style={styles.input} /><TextInput value={content} onChangeText={setContent} placeholder="Votre message" multiline style={[styles.input, styles.message]} /><Pressable disabled={sending} onPress={send} style={({ pressed }) => [styles.primary, pressed && { opacity: .75 }]}><Send color="#fff" size={17} /><Text style={styles.primaryLabel}>{sending ? 'Envoi…' : 'Envoyer'}</Text></Pressable></View>{!messages.length ? <View style={styles.empty}><Text style={styles.emptyTitle}>Aucun message reçu</Text><Text style={styles.emptyText}>Les nouveaux messages de votre école apparaîtront ici.</Text></View> : <FlatList data={messages} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} renderItem={({ item }) => <View style={styles.row}><Text style={styles.body}>{item.contenu}</Text><Text style={styles.meta}>De {item.expediteurId}</Text></View>} />}</ScreenContainer>;
}

const styles = StyleSheet.create({ heading: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, eyebrow: { color: '#7a5ba4', fontSize: 11, fontWeight: '800', letterSpacing: 1 }, title: { color: '#24114d', fontSize: 28, fontWeight: '800', marginTop: 5 }, caption: { color: '#756b84', fontSize: 14, lineHeight: 20, marginTop: 4 }, compose: { backgroundColor: '#fff', borderRadius: 18, gap: 9, marginVertical: 16, padding: 16 }, input: { backgroundColor: '#f7f4ff', borderColor: '#e6ddf6', borderRadius: 12, borderWidth: 1, color: '#24114d', padding: 12 }, message: { minHeight: 80, textAlignVertical: 'top' }, primary: { alignItems: 'center', backgroundColor: '#630ed4', borderRadius: 13, flexDirection: 'row', gap: 7, justifyContent: 'center', padding: 13 }, primaryLabel: { color: '#fff', fontWeight: '800' }, list: { gap: 9, paddingBottom: 40 }, row: { backgroundColor: '#fff', borderRadius: 16, gap: 6, padding: 15 }, body: { color: '#24114d', fontSize: 15 }, meta: { color: '#756b84', fontSize: 12 }, empty: { alignItems: 'center', backgroundColor: '#fff', borderRadius: 18, padding: 25 }, emptyTitle: { color: '#24114d', fontSize: 17, fontWeight: '800' }, emptyText: { color: '#756b84', marginTop: 8, textAlign: 'center' } });
