import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { CameraView, useCameraPermissions, type BarcodeScanningResult } from 'expo-camera';
import { httpsCallable } from 'firebase/functions';
import { functions } from '../lib/firebase';
import { ScreenContainer } from '../components/ScreenContainer';

export default function QrScreen() {
  const [permission, requestPermission] = useCameraPermissions();
  const [scanning, setScanning] = useState(false);
  const [busy, setBusy] = useState(false);
  const [lastResult, setLastResult] = useState('Aucun scan effectué.');
  const scan = async ({ data }: BarcodeScanningResult) => { if (!data || busy) return; setBusy(true); try { const payload = JSON.parse(data) as { tokenId?: string; schoolId?: string }; if (!payload.tokenId || !payload.schoolId) throw new Error('invalid'); if (functions) await httpsCallable(functions, 'consumeQrToken')({ tokenId: payload.tokenId, schoolId: payload.schoolId }); setLastResult('Accès validé. Le jeton a été consommé une seule fois.'); setScanning(false); } catch { setLastResult('QR refusé : invalide, expiré ou déjà utilisé.'); Alert.alert('Accès refusé', 'Le QR Code ne peut pas être utilisé.'); } finally { setBusy(false); } };
  const open = async () => { if (!permission?.granted) { const result = await requestPermission(); if (!result.granted) { Alert.alert('Caméra nécessaire', 'Autorisez la caméra dans les réglages de l’appareil.'); return; } } setScanning(true); };
  if (scanning) return <View style={styles.camera}><CameraView style={StyleSheet.absoluteFill} barcodeScannerSettings={{ barcodeTypes: ['qr'] }} onBarcodeScanned={busy ? undefined : scan} /><View style={styles.overlay}><Text style={styles.cameraTitle}>Scanner un accès</Text><View style={styles.frame} /><Text style={styles.cameraCaption}>Placez le QR Code au centre du cadre.</Text><Pressable style={styles.outline} onPress={() => setScanning(false)}><Text style={styles.outlineLabel}>Annuler</Text></Pressable></View></View>;
  return <ScreenContainer><Text style={styles.eyebrow}>ACCÈS TEMPORAIRE</Text><Text style={styles.title}>Scanner un QR Code</Text><Text style={styles.caption}>Les jetons sont vérifiés côté serveur lorsqu’une connexion Firebase est disponible.</Text><View style={styles.card}><Text style={styles.cardTitle}>Connexion personnel</Text><Text style={styles.cardText}>{lastResult}</Text><Pressable style={styles.primary} onPress={open}><Text style={styles.primaryLabel}>Ouvrir la caméra</Text></Pressable></View><View style={styles.notice}><Text style={styles.noticeTitle}>Sécurité</Text><Text style={styles.noticeText}>Un QR est valable 15 minutes et ne peut être consommé qu’une seule fois.</Text></View></ScreenContainer>;
}

const styles = StyleSheet.create({ eyebrow: { color: '#7a5ba4', fontSize: 11, fontWeight: '800', letterSpacing: .8 }, title: { color: '#24114d', fontSize: 28, fontWeight: '800', marginTop: 6 }, caption: { color: '#756b84', fontSize: 14, lineHeight: 21, marginTop: 4 }, card: { backgroundColor: '#fff', borderRadius: 22, gap: 14, padding: 20 }, cardTitle: { color: '#24114d', fontSize: 19, fontWeight: '800' }, cardText: { color: '#756b84', lineHeight: 20 }, primary: { alignItems: 'center', backgroundColor: '#630ed4', borderRadius: 14, padding: 14 }, primaryLabel: { color: '#fff', fontWeight: '800' }, notice: { backgroundColor: '#edf9f5', borderColor: '#c9eee1', borderRadius: 18, borderWidth: 1, gap: 6, padding: 16 }, noticeTitle: { color: '#087454', fontWeight: '800' }, noticeText: { color: '#376e60', lineHeight: 19 }, camera: { backgroundColor: '#14101a', flex: 1 }, overlay: { alignItems: 'center', backgroundColor: 'rgba(20,16,26,.46)', flex: 1, gap: 14, justifyContent: 'center', padding: 24 }, cameraTitle: { color: '#fff', fontSize: 22, fontWeight: '800' }, frame: { borderColor: '#994cff', borderRadius: 22, borderWidth: 3, height: 260, width: 260 }, cameraCaption: { color: '#f0eaff' }, outline: { borderColor: '#fff', borderRadius: 14, borderWidth: 1, paddingHorizontal: 30, paddingVertical: 12 }, outlineLabel: { color: '#fff', fontWeight: '800' } });
