import { useEffect, useMemo, useState } from 'react';
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { CalendarCheck, CheckCircle2, Clock3 } from 'lucide-react-native';
import { collection, onSnapshot } from 'firebase/firestore';
import { httpsCallable } from 'firebase/functions';
import { auth, db, functions } from '../../../lib/firebase';
import { enqueue, flushQueue } from '../../../lib/offlineQueue';
import { ScreenContainer } from '../../../components/ScreenContainer';

type Status = 'present' | 'late' | 'absent' | 'excused';
type Student = { id: string; name: string; classeId: string };
type Lesson = { id: string; classeId: string; classeName: string; matiereId: string; subject: string; day: string; start: string; end: string };

function isActive(lesson: Lesson, now = new Date()) { const days = ['DIMANCHE', 'LUNDI', 'MARDI', 'MERCREDI', 'JEUDI', 'VENDREDI', 'SAMEDI']; if (lesson.day.toUpperCase() !== days[now.getDay()]) return false; const current = now.getHours() * 60 + now.getMinutes(); const [startHour, startMinute] = lesson.start.split(':').map(Number); const [endHour, endMinute] = lesson.end.split(':').map(Number); return current >= startHour * 60 + startMinute && current < endHour * 60 + endMinute; }

export default function AttendanceScreen() {
  const [students, setStudents] = useState<Student[]>([]);
  const [lessons, setLessons] = useState<Lesson[]>([]);
  const [records, setRecords] = useState<Record<string, Status>>({});
  const [saving, setSaving] = useState(false);
  const [pending, setPending] = useState(0);
  useEffect(() => { const callableFunctions = functions; if (callableFunctions) void flushQueue(async (callable, payload) => { await httpsCallable(callableFunctions, callable)(payload); }).then((result) => setPending(result.pending)); }, []);
  useEffect(() => {
    let stops: Array<() => void> = [];
    const load = async () => { if (!db || !auth?.currentUser) return; const claims = await auth.currentUser.getIdTokenResult(); const schoolId = String(claims.claims.school_id ?? ''); if (!schoolId) return;
      stops = [onSnapshot(collection(db, 'ecoles', schoolId, 'eleves'), (snapshot) => setStudents(snapshot.docs.map((item) => { const data = item.data(); return { id: item.id, name: String(data.name ?? data.nom ?? item.id), classeId: String(data.classeId ?? data.className ?? '') }; }))), onSnapshot(collection(db, 'ecoles', schoolId, 'planning'), (snapshot) => setLessons(snapshot.docs.map((item) => { const data = item.data(); return { id: item.id, classeId: String(data.classeId ?? data.className ?? ''), classeName: String(data.classeName ?? data.className ?? data.classeId ?? ''), matiereId: String(data.matiereId ?? data.subject ?? ''), subject: String(data.subject ?? data.matiere ?? data.matiereId ?? ''), day: String(data.day ?? data.jour ?? ''), start: String(data.start ?? data.heureDebut ?? ''), end: String(data.end ?? data.heureFin ?? '') }; })) )];
    }; void load(); return () => stops.forEach((stop) => stop());
  }, []);
  const activeLesson = useMemo(() => lessons.find((lesson) => isActive(lesson)) ?? null, [lessons]);
  const activeStudents = useMemo(() => activeLesson ? students.filter((student) => student.classeId === activeLesson.classeId) : [], [activeLesson, students]);
  const save = async () => { if (!activeLesson || !activeStudents.length) return; setSaving(true); const payload = { dateKey: new Date().toISOString().slice(0, 10), records: activeStudents.map((student) => ({ studentId: student.id, status: records[student.id] ?? 'present', slotId: activeLesson.id, classeId: activeLesson.classeId, matiereId: activeLesson.matiereId })) }; try { if (functions) await httpsCallable(functions, 'writeAttendanceBatch')(payload); else { await enqueue('writeAttendanceBatch', payload); setPending((value) => value + 1); } Alert.alert('Appel enregistré', pending ? 'L’appel est en attente de synchronisation.' : 'Les présences ont été enregistrées.'); } catch { await enqueue('writeAttendanceBatch', payload); setPending((value) => value + 1); Alert.alert('Hors connexion', 'L’appel est conservé sur cet appareil.'); } finally { setSaving(false); } };

  return <ScreenContainer><View style={styles.heading}><View><Text style={styles.eyebrow}>APPEL DU JOUR</Text><Text style={styles.title}>{activeLesson?.classeName ?? 'Aucun créneau actif'}</Text><Text style={styles.caption}>{activeLesson ? `${activeLesson.day} · ${activeLesson.subject} · ${activeLesson.start}–${activeLesson.end}` : 'L’appel s’ouvre automatiquement pendant un créneau de votre planning.'}</Text></View><CalendarCheck color="#630ed4" size={28} /></View>{!activeLesson ? <View style={styles.empty}><Clock3 color="#f59e0b" size={26} /><Text style={styles.emptyTitle}>Aucun appel disponible maintenant</Text><Text style={styles.emptyText}>Le système n’autorise l’appel que pour une classe, une matière et un horaire qui vous sont affectés.</Text></View> : !activeStudents.length ? <View style={styles.empty}><Text style={styles.emptyTitle}>Aucun élève dans ce contexte</Text><Text style={styles.emptyText}>Vérifiez les inscriptions de la classe active.</Text></View> : <FlatList data={activeStudents} keyExtractor={(student) => student.id} contentContainerStyle={styles.list} renderItem={({ item: student }) => <View style={styles.row}><Text style={styles.name}>{student.name}</Text><View style={styles.statuses}>{(['present', 'late', 'absent', 'excused'] as Status[]).map((status) => <Pressable key={status} onPress={() => setRecords((current) => ({ ...current, [student.id]: status }))} style={({ pressed }) => [styles.status, records[student.id] === status && styles.selected, pressed && styles.pressed]}><Text style={[styles.statusLabel, records[student.id] === status && styles.selectedLabel]}>{status === 'present' ? 'Présent' : status === 'late' ? 'Retard' : status === 'absent' ? 'Absent' : 'Excusé'}</Text></Pressable>)}</View></View>} />}{activeLesson && activeStudents.length > 0 && <Pressable disabled={saving} style={styles.primary} onPress={save}><CheckCircle2 color="#fff" size={18} /><Text style={styles.primaryLabel}>{saving ? 'Enregistrement…' : 'Enregistrer l’appel'}</Text></Pressable>}{pending > 0 && <Text style={styles.pending}>{pending} opération(s) en attente de synchronisation</Text>}</ScreenContainer>;
}

const styles = StyleSheet.create({ heading: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, eyebrow: { color: '#7a5ba4', fontSize: 11, fontWeight: '800', letterSpacing: 1 }, title: { color: '#24114d', fontSize: 28, fontWeight: '800', marginTop: 5 }, caption: { color: '#756b84', fontSize: 14, lineHeight: 20, marginTop: 4 }, list: { gap: 10, paddingBottom: 90 }, row: { backgroundColor: '#fff', borderRadius: 18, gap: 11, padding: 15 }, name: { color: '#24114d', fontSize: 15, fontWeight: '800' }, statuses: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 }, status: { borderColor: '#e6ddf6', borderRadius: 10, borderWidth: 1, paddingHorizontal: 8, paddingVertical: 7 }, selected: { backgroundColor: '#630ed4', borderColor: '#630ed4' }, pressed: { opacity: .75 }, statusLabel: { color: '#756b84', fontSize: 11, fontWeight: '700' }, selectedLabel: { color: '#fff' }, primary: { alignItems: 'center', backgroundColor: '#630ed4', borderRadius: 14, flexDirection: 'row', gap: 8, justifyContent: 'center', padding: 15 }, primaryLabel: { color: '#fff', fontWeight: '800' }, pending: { color: '#b16d00', fontSize: 12, textAlign: 'center' }, empty: { alignItems: 'center', backgroundColor: '#fff', borderRadius: 18, gap: 8, padding: 26 }, emptyTitle: { color: '#24114d', fontSize: 17, fontWeight: '800', textAlign: 'center' }, emptyText: { color: '#756b84', lineHeight: 20, textAlign: 'center' } });
