import { useEffect, useMemo, useState } from 'react';
import { Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { ReceiptText, Search, WalletCards } from 'lucide-react-native';
import { collection, onSnapshot } from 'firebase/firestore';
import { httpsCallable } from 'firebase/functions';
import { auth, db, functions } from '../../../lib/firebase';
import { enqueue } from '../../../lib/offlineQueue';
import { ScreenContainer } from '../../../components/ScreenContainer';

type Student = { id: string; name: string; code: string; className: string };

export default function PaymentsScreen() {
  const [students, setStudents] = useState<Student[]>([]);
  const [query, setQuery] = useState('');
  const [studentId, setStudentId] = useState('');
  const [amount, setAmount] = useState('');
  const [method, setMethod] = useState('Espèces');
  const [reference, setReference] = useState('');
  const [saving, setSaving] = useState(false);
  useEffect(() => { let stop: () => void = () => undefined; const load = async () => { if (!db || !auth?.currentUser) return; const claims = await auth.currentUser.getIdTokenResult(); const schoolId = String(claims.claims.school_id ?? ''); if (!schoolId) return; stop = onSnapshot(collection(db, 'ecoles', schoolId, 'eleves'), (snapshot) => setStudents(snapshot.docs.map((item) => { const data = item.data(); return { id: item.id, name: String(data.name ?? data.nom ?? item.id), code: String(data.codeUnique ?? data.code ?? item.id), className: String(data.className ?? data.classeId ?? '') }; }))); }; void load(); return () => stop(); }, []);
  const matches = useMemo(() => students.filter((student) => `${student.name} ${student.code} ${student.className}`.toLowerCase().includes(query.toLowerCase())).slice(0, 6), [students, query]);
  const selected = students.find((student) => student.id === studentId);
  const save = async () => { const parsed = Number(amount); if (!selected || !Number.isFinite(parsed) || parsed <= 0) { Alert.alert('Informations incomplètes', 'Sélectionnez un élève et saisissez un montant positif.'); return; } if (method === 'Mobile Money' && !reference.trim()) { Alert.alert('Référence requise', 'Ajoutez la référence de transaction Mobile Money.'); return; } const payload = { id: `payment-${selected.id}-${Date.now()}`, studentId: selected.id, eleveId: selected.id, amount: parsed, montantPaye: parsed, method, motif: 'Mensualité', referenceTransaction: reference.trim() || null, datePaiement: new Date().toISOString() }; setSaving(true); try { if (functions) await httpsCallable(functions, 'recordPayment')(payload); else await enqueue('recordPayment', payload); Alert.alert('Paiement enregistré', 'L’encaissement est enregistré avec sa référence.'); setAmount(''); setReference(''); setStudentId(''); setQuery(''); } catch { await enqueue('recordPayment', payload); Alert.alert('Hors connexion', 'Le paiement est conservé sur cet appareil et sera synchronisé automatiquement.'); } finally { setSaving(false); } };
  return <ScreenContainer><View style={styles.heading}><View><Text style={styles.eyebrow}>COMPTABILITÉ</Text><Text style={styles.title}>Nouveau paiement</Text><Text style={styles.caption}>Aucun paiement n’est validé sans élève et montant identifiés.</Text></View><WalletCards color="#0f9f78" size={28} /></View><View style={styles.card}><Text style={styles.label}>Rechercher un élève</Text><View style={styles.search}><Search color="#617b72" size={17} /><TextInput value={selected ? selected.name : query} onChangeText={(value) => { setQuery(value); setStudentId(''); }} style={styles.searchInput} placeholder="Nom, code ou classe" /></View>{!selected && query.length > 0 && <FlatList data={matches} keyExtractor={(item) => item.id} keyboardShouldPersistTaps="handled" renderItem={({ item }) => <Pressable style={styles.result} onPress={() => { setStudentId(item.id); setQuery(item.name); }}><Text style={styles.resultName}>{item.name}</Text><Text style={styles.resultMeta}>{item.code} · {item.className}</Text></Pressable>} />}{selected && <View style={styles.selected}><ReceiptText color="#0f9f78" size={18} /><Text style={styles.resultName}>{selected.name}<Text style={styles.resultMeta}> · {selected.className}</Text></Text></View>}<Text style={styles.label}>Montant (CDF)</Text><TextInput value={amount} onChangeText={setAmount} keyboardType="number-pad" style={styles.input} placeholder="250000" /><Text style={styles.label}>Mode</Text><View style={styles.methods}>{['Espèces', 'Mobile Money', 'Virement'].map((item) => <Pressable key={item} style={({ pressed }) => [styles.method, method === item && styles.methodSelected, pressed && { opacity: .75 }]} onPress={() => setMethod(item)}><Text style={[styles.methodLabel, method === item && styles.methodSelectedLabel]}>{item}</Text></Pressable>)}</View>{method === 'Mobile Money' && <><Text style={styles.label}>Référence de transaction</Text><TextInput value={reference} onChangeText={setReference} style={styles.input} placeholder="Référence fournie par l’opérateur" /></>}<Pressable disabled={saving} style={styles.primary} onPress={save}><Text style={styles.primaryLabel}>{saving ? 'Enregistrement…' : 'Valider le paiement'}</Text></Pressable></View></ScreenContainer>;
}

const styles = StyleSheet.create({ heading: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, eyebrow: { color: '#0f9f78', fontSize: 11, fontWeight: '800', letterSpacing: 1 }, title: { color: '#143c34', fontSize: 28, fontWeight: '800', marginTop: 5 }, caption: { color: '#617b72', fontSize: 14, lineHeight: 20, marginTop: 4 }, card: { backgroundColor: '#fff', borderRadius: 20, gap: 10, padding: 18 }, label: { color: '#367a68', fontSize: 11, fontWeight: '800', marginTop: 6, textTransform: 'uppercase' }, search: { alignItems: 'center', backgroundColor: '#f1faf7', borderColor: '#d9eee6', borderRadius: 12, borderWidth: 1, flexDirection: 'row', gap: 7, paddingHorizontal: 12 }, searchInput: { color: '#143c34', flex: 1, paddingVertical: 12 }, result: { borderBottomColor: '#e5f1ec', borderBottomWidth: 1, paddingVertical: 10 }, resultName: { color: '#143c34', fontWeight: '800' }, resultMeta: { color: '#617b72', fontSize: 12 }, selected: { alignItems: 'center', backgroundColor: '#ecfdf5', borderRadius: 12, flexDirection: 'row', gap: 9, padding: 12 }, input: { backgroundColor: '#f1faf7', borderColor: '#d9eee6', borderRadius: 12, borderWidth: 1, color: '#143c34', padding: 13 }, methods: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, method: { borderColor: '#d9eee6', borderRadius: 10, borderWidth: 1, padding: 9 }, methodSelected: { backgroundColor: '#0f9f78', borderColor: '#0f9f78' }, methodLabel: { color: '#617b72', fontSize: 12, fontWeight: '700' }, methodSelectedLabel: { color: '#fff' }, primary: { alignItems: 'center', backgroundColor: '#0f9f78', borderRadius: 14, padding: 15 }, primaryLabel: { color: '#fff', fontWeight: '800' } });
