import { useEffect, useState, type FormEvent } from 'react';
import { collection, onSnapshot, orderBy, query, where } from 'firebase/firestore';
import { httpsCallable, type Functions } from 'firebase/functions';
import { ChevronRight, Mail, Plus, RefreshCw } from 'lucide-react';
import { auth, db } from '../lib/firebase';

type Message = { id: string; from: string; fromId: string; content: string; date: string; read: boolean };

export function RealtimeMessagesPage({ functions, schoolId, onNotify }: { functions: Functions | null; schoolId: string; onNotify: (message: string, tone?: 'success' | 'error' | 'info') => void }) {
  const [messages, setMessages] = useState<Message[]>([]);
  const [showCompose, setShowCompose] = useState(false);
  const [recipientId, setRecipientId] = useState('');
  const [content, setContent] = useState('');
  useEffect(() => { if (!db || !schoolId || !auth?.currentUser) return undefined; const currentUserId = auth.currentUser.uid; const messagesQuery = query(collection(db, 'ecoles', schoolId, 'messages'), where('destinataireId', '==', currentUserId), orderBy('createdAt', 'desc')); return onSnapshot(messagesQuery, (snapshot) => setMessages(snapshot.docs.map((item) => { const data = item.data(); const created = data.createdAt as { toDate?: () => Date } | undefined; return { id: item.id, from: String(data.expediteurId ?? 'Utilisateur'), fromId: String(data.expediteurId ?? ''), content: String(data.contenu ?? data.content ?? ''), date: created?.toDate?.().toLocaleString('fr-FR') ?? 'À l’instant', read: Boolean(data.lu ?? data.read) }; })), () => setMessages([])); }, [schoolId]);
  const send = async (event: FormEvent) => { event.preventDefault(); if (!recipientId.trim() || !content.trim()) return; if (!functions) { onNotify('Firebase doit être configuré pour envoyer un message.', 'error'); return; } try { await httpsCallable(functions, 'sendMessage')({ destinataireId: recipientId.trim(), contenu: content.trim() }); setContent(''); setRecipientId(''); setShowCompose(false); onNotify('Message envoyé.'); } catch { onNotify('Impossible d’envoyer le message.', 'error'); } };
  const markRead = async (message: Message) => { setMessages((current) => current.map((item) => item.id === message.id ? { ...item, read: true } : item)); if (functions) { try { await httpsCallable(functions, 'markMessageRead')({ messageId: message.id }); } catch { onNotify('Le message reste en attente de synchronisation.', 'error'); } } };
  return <><div className="page-intro"><div><p className="eyebrow">Communication · temps réel</p><h1>Messagerie</h1><p>Les conversations sont filtrées par établissement et par utilisateur.</p></div><button className="button primary" onClick={() => setShowCompose(true)}><Plus size={17} /> Nouveau message</button></div><div className="messages-layout"><section className="panel conversation-list"><div className="panel-heading"><div><p className="eyebrow">Boîte de réception</p><h2>{messages.length} message(s)</h2></div><button className="icon-button" onClick={() => onNotify('La boîte de réception est synchronisée par Firestore.', 'info')}><RefreshCw size={16} /></button></div>{messages.length ? messages.map((message) => <button className={`conversation ${message.read ? '' : 'unread'}`} key={message.id} onClick={() => void markRead(message)}><span className="avatar">{message.from.slice(0, 2).toUpperCase()}</span><span><strong>{message.from}</strong><small>{message.content}</small><time>{message.date}</time></span><ChevronRight size={16} /></button>) : <div className="empty-state"><Mail size={30} /><h3>Aucun message reçu</h3><p>Les nouveaux échanges de votre établissement apparaîtront ici.</p></div>}</section><section className="panel message-placeholder"><Mail size={36} /><h2>Une communication simple</h2><p>Sélectionnez un message pour le marquer comme lu ou composez un nouvel échange.</p><button className="button secondary" onClick={() => setShowCompose(true)}>Écrire un message</button></section></div>{showCompose && <div className="modal-backdrop" role="presentation"><div className="modal" role="dialog" aria-modal="true" aria-label="Nouveau message"><div className="modal-head"><div><p className="eyebrow">CLASSE</p><h2>Nouveau message</h2></div><button className="icon-button" onClick={() => setShowCompose(false)} aria-label="Fermer">×</button></div><form className="modal-form" onSubmit={send}><label>Identifiant du destinataire<input value={recipientId} onChange={(event) => setRecipientId(event.target.value)} placeholder="UID Firebase du collègue" /></label><label>Message<textarea value={content} onChange={(event) => setContent(event.target.value)} rows={5} placeholder="Votre message…" /></label><div className="modal-actions"><button type="button" className="button secondary" onClick={() => setShowCompose(false)}>Annuler</button><button className="button primary"><Mail size={16} /> Envoyer</button></div></form></div></div>}</>;
}
